### ISSUE TITLE
Any way to update the `plugins_dir` in the `config.toml`

### ISSUE THREAD

**Issue by chenrui333** [triyanox/lla#10]
👋 While [packaging lla for homebrew](https://github.com/Homebrew/homebrew-core/pull/199192), I found that there is no commands to help update `plugins_dir`, is that desired? Thanks!

**Comment by triyanox** [comment]
Thank you @chenrui333 for opening this issue, I already add the `config --set` subcommand for updating the `lla` config you can update to `v0.2.7` to use the new command!

Thanks again @chenrui333!

**Comment by chenrui333** [comment]
Sounds great, thanks!

**Comment by triyanox** [comment]
For sure @chenrui333 any future suggestions are welcome, thanks again!
