### ISSUE TITLE
Using -R and -l together doesn't work as expected

### ISSUE THREAD

**Issue by deverl** [triyanox/lla#12]
Probably a misunderstanding on my part...

When I use `lla -lR` it lists all of the files, but just the file name. It loses the long listing format.

Also, it doesn't give any indication of the path to the files.

If I use `ls -lR`, the directory path is printed out followed by the directory's contents, in long listing format.

Not sure if that is expected or not.

**Comment by triyanox** [comment]
Thanks again @deverl for opening this issue, currently, when combining recursive `-R` and long `-l` flags, lla prioritizes the recursive listing but loses the long format details and path context. This was initially designed this way to provide a simplified view of all files, but I agree that maintaining the long format and directory context would be more useful and consistent with user expectations. I will consider including this in the upcoming releases for sure !

**Comment by triyanox** [comment]
Hey @deverl just release `v0.2.10` and removed the `-R` flag because confuses user you can now directly use the `--tree` or `-t` because the tree view uses the recursive listing under the hood.

Thanks again for opening this issue
