### ISSUE TITLE
Github release tags

### ISSUE THREAD

**Issue by 0323pin** [triyanox/lla#2]
Hi,

Did you stop providing Github release tags?
I've changed the source to crates.io but, in order to maintain the package up-to-date, it's better with tags here. Github provides RSS feeds that I can use, something that crates.io does not, AFAIK.

Regards.

**Comment by triyanox** [comment]
Hi @0323pin,

Yes for sure I just created a new release tag for the latest version, thank you for opening this issue !
I will add a Github Action to automate creating tags and release as well as publish to crates.io in the next release.

Best regards

**Comment by 0323pin** [comment]
Thank you.

**Comment by 0323pin** [comment]
Hi again @triyanox 

I'm sorry for being _that guy_ but, the versions are out of sync.

> Github: 0.1.6
> crates.io: 0.1.7

**Comment by triyanox** [comment]
Hi @0323pin 

My bad I fixed it I created the correct one thank you for pointing the issue much appreciated !

**Comment by 0323pin** [comment]
Hi,

I just realized crates.io is at 0.2.2 but, Github is still 0.1.7
Would you prefer if I just track releases in crates.io?
I've missed updates from 0.1.7 up to now because, I haven't found a way of tracking releases from crates.io via RSS

**Comment by 0323pin** [comment]
I'll try to get our (NetBSD) package up-to-date within the next 24 h

**Comment by triyanox** [comment]
Thank you @0323pin for the heads-up I will create an automated release/publish workflow in the future so the version in crates.io will be matching the github's. For now I created the release for `v2.2.0`.

**Comment by 0323pin** [comment]
Thanks 👍
