### ISSUE TITLE
🔴 Some Small Suggestions

### ISSUE THREAD

**Issue by Thomas-Harrell** [triyanox/lla#44]
---

Hello Developer, 

I really enjoy the lla you’ve developed. 

However, I encountered a few small issues while using it.

---

On my computer, I use iTerm2 as the terminal and the Ayu Light theme as the terminal color preset.

Sometimes, the text color output by lla can be difficult to read and a bit harsh on the eyes.

Although I understand this could be resolved by using dark mode or switching to a different color preset.

Are there any plans to introduce some options for modifying the color of the lla output, for a more friendly accessibility experience or some modifications to the color body or something like that?

---

On my server, I use CentOS as the operating system.

Since it is an older system, I encountered the error `/lib64/libm.so.6: version GLIBC_2.29 not found` while using lla.  

The version of lla I am using is: `https://github.com/triyanox/lla/releases/download/v0.2.10/lla-linux-amd64`.

It seems like this issue can only be resolved by upgrading the version of glibc.

However, upgrading glibc on CentOS appears to involve some unpredictable risks, so I haven’t attempted it.

I would like to ask if there are any other ways to resolve this issue.

---

Some examples of the above additions, hopefully with some help

[https://github.com/sharkdp/bat?tab=readme-ov-file#customization](https://github.com/sharkdp/bat?tab=readme-ov-file#customization)

[https://github.com/sharkdp/bat?tab=readme-ov-file#troubleshooting](https://github.com/sharkdp/bat?tab=readme-ov-file#troubleshooting)

---

About WCAG

[https://webaim.org/resources/contrastchecker](https://webaim.org/resources/contrastchecker)

---

**Comment by Bill-Costa** [comment]
Just another note about color.  The default color scheme doesn't work well with a light colored terminal background.  Adding color options can be a huge project in and of itself, so I'd like to suggest an option/configuration setting to simply turn off the use of color.

**Comment by pedronavf** [comment]
> so I'd like to suggest an option/configuration setting to simply turn off the use of color.

@Bill-Costa, for now you can use the [NO_COLOR](https://no-color.org/) environment variable: `NO_COLOR=1 lla`

**Comment by Bill-Costa** [comment]
Thanks for this and in particular "NO_COLOR" web reference.  Good to know!

**Comment by triyanox** [comment]
Hey there @Thomas-Harrell @Bill-Costa @pedronavf Thank you for taking the time to provide those awesome suggestions, definitely will be considered for the upcoming releases, starting with the `themes` feature to make easy to customize how `lla` looks including support for light themed terminals

**Comment by triyanox** [comment]
Hey there @Thomas-Harrell @Bill-Costa @pedronavf I just released [v0.3.5](https://github.com/triyanox/lla/releases/tag/v0.3.5) which has theme support and the `--no-color` flag that works with all listing formats, also you can create your own themes or use the pre-made ones in the [here](https://github.com/triyanox/lla/tree/main/themes)

**Comment by Bill-Costa** [comment]
Wow -- adding color theme support is a non-trivial effort.  **Bravo!**  And the new command line option is a sensible and welcomed addition.  The environment variable is useful too, but being able to control the use of color for each command invocation is very convenient for scripting.  Thanks!!

**Comment by triyanox** [comment]
Thank you @Thomas-Harrell @Bill-Costa for taking the time to provide those awesome suggestions!

> @triyanox
> 
> Thank you for your work.
> 
> And a little advice.
> 
> You can also add a theme for Monokai Pro!
> 
> https://monokai.pro/iterm

@Thomas-Harrell I will definitely add the monokai theme and other widely used theme for sure!

> Wow -- adding color theme support is a non-trivial effort. **Bravo!** And the new command line option is a sensible and welcomed addition. The environment variable is useful too, but being able to control the use of color for each command invocation is very convenient for scripting. Thanks!!

@Bill-Costa I will include a new config option for `no_color` to make it easy to disable color once, expect it in the upcoming release. Also you can set the theme to `none` and it will fall back to use simple theming scheme which has a good contrast across the majority of terminals, another good suggestion for you now you can alias you most used lla commands
