### ISSUE TITLE
`lla init` fails with "Plugin directory does not exist"

### ISSUE THREAD

**Issue by Chaz6** [triyanox/lla#7]
```bash
cargo install lla
lla init

# Error: Plugin("Plugin directory does not exist: \"/home/chaz/.config/lla/plugins\"")
```

**Comment by triyanox** [comment]
Thank you @Chaz6 for opening this issue! The issue is fixed on v0.2.6 you will be able to use the `init` command without any problems by running `cargo install lla` to get the new update
